### ISSUE TITLE
bitrise setup fails on brew doctor warnings

### ISSUE THREAD

**Issue by rickw** [bitrise-io/bitrise#338]
Running setup fails because of this warning from brew:

WARN[15:13:58] Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Unexpected header files:
    /usr/local/include/python2.7/greenlet/greenlet.h 
FATA[15:13:58] Setup failed: Homebrew not installed or has some issues. Please fix these before calling setup again. Err:Failed to: brew doctor

This is an expected warning when installing packages with PIP. Bitrise setup should not fail on this type of warning.

**Comment by viktorbenei** [comment]
You can skip the Homebrew doctor check by running: `bitrise setup -minimal`.

We'll add a not about this flag in the upcoming version of the CLI.

**Comment by rickw** [comment]
thanks!
