### ISSUE TITLE
Support env variables in triggers

### ISSUE THREAD

**Issue by samgro** [bitrise-io/bitrise#351]
We create a new branch for every release, and have several different workflows that we'd like to run in our release branch. It would be nice to just update the name of the branch in one place and have different triggers for it.

**Comment by viktorbenei** [comment]
You can use wildcard "*" in the patterns. Is that not an option? Something like: `pattern: release/*` which would match `release/1.0.0`, `release/a`, ... ?

**Comment by samgro** [comment]
what about "batman-rb-*"? is that a valid pattern?

**Comment by viktorbenei** [comment]
Sure it is, the * can be anywhere 😉

**Comment by samgro** [comment]
great, i think that should pretty effectively encompass my use case.

**Comment by viktorbenei** [comment]
Yeah, it seems like the wildcard is the best way to solve this :)
