### ISSUE TITLE
Unable to access envs if the steps is defined as path::

### ISSUE THREAD

**Issue by sudhanshuraheja** [bitrise-io/bitrise#352]
I have a workflow which is defined as follows. No matter where I define the envs, the step which is in an external file never sees it. Any pointers on this would help.

https://cloudup.com/cIOrNa_mFOd

**Comment by viktorbenei** [comment]
please provide the error / output, also the `step.yml` and the code of the step

if you can see the env in the "hello" script (where you print `${debug}`, in a script step) then it should be available in your & other steps too - so the issue is most likely in your step's code or maybe in the `step.yml` (if it overwrites the value)

**Comment by sudhanshuraheja** [comment]
1. I can't read the values in the my script, so there's no error per se. But I was hoping I'll be able to read the envs in step.sh

2. I have this in my step.sh
https://cloudup.com/cPFAfs1WtUD

And this is my step.yml
https://cloudup.com/c-Gx0QmuzUm

I'm sorry if I've missed anything obvious?

**Comment by viktorbenei** [comment]
Did you try to print the value of $debug in step.sh?

AFAIK "set -v" can't be indented in an if, so it might not be an issue with the env at all

**Comment by sudhanshuraheja** [comment]
It strangely gives me nothing when I print the value of $debug in step.sh.

If the use the script step and copy the code to bitrise.yml, then I can indent set -v!

It's also possible that I messed something up which trying to stepman share somewhere. Let me try and replicate this on another machine.

**Comment by viktorbenei** [comment]
btw as this (`debug`) is an input of the step, you might want to try to include the value in your bitrise.yml as an input of the step.

So, you can either define it directly for the step as an input (in `bitrise.yml`), or if you want to reference an App Env Var or Workflow env var you can do this: `- debug: $debug`

**Comment by sudhanshuraheja** [comment]
Interesting, thanks!

**Comment by viktorbenei** [comment]
Did you manage to solve this issue?

**Comment by sudhanshuraheja** [comment]
Yes, closing this issue.

**Comment by viktorbenei** [comment]
Was this related to Bitrise? Could we improve something?

**Comment by sudhanshuraheja** [comment]
No, my setup was strange. I removed it, started again and it worked :)

**Comment by viktorbenei** [comment]
Thanks, and Happy Building! 😎

**Comment by sudhanshuraheja** [comment]
I was actually looking through the CLI tool to figure out if you could help me build apps, and I found that CI's won't let you do that. So I started working on a script for iOS and Android - https://github.com/leftshifters/upshift - which would take over after bitrise-ci.yml leaves you at the correct place.

I'll get back to try things again after I'm done with that :)

And loved the CLI tool, it is just awesome.

**Comment by viktorbenei** [comment]
Got it, thanks again, and let us know if we can help with anything!
