### ISSUE TITLE
Bitrise setup waits for all brew doctor issues to be closed before it can run setup

### ISSUE THREAD

**Issue by sudhanshuraheja** [bitrise-io/bitrise#353]
Alright, so this has left me in a hard place.

To run bitrise setup, I need "brew doctor" to complete without any warnings - https://cloudup.com/c1Z5bKO8n8r

Brew doctor on the other hard, is asking me to install a newer version of Xcode - 7.3.1, but there is none available on the AppStore - https://cloudup.com/c1Z5bKO8n8r

Can we have a setting to turn off this dependency on Brew.

**Comment by viktorbenei** [comment]
You can run `bitrise setup -minimal` to skip the `brew doctor` checks
