### ISSUE TITLE
need a help with this error

### ISSUE THREAD

**Issue by iceman201** [bitrise-io/bitrise#366]
>FATA[04:04:07] Analyzer failed, error: out: /tmp/bitrise-plugin-init992597450/podfile.rb:92:in >`basename': no implicit conversion of nil into String (TypeError)
>	from /tmp/bitrise-plugin-init992597450/podfile.rb:92:in `fix_targets'
>	from /tmp/bitrise-plugin-init992597450/podfile.rb:124:in `list_targets'
>	from /tmp/bitrise-plugin-init992597450/get_workspace.rb:7:in `<main>', err: exit status 1 

I receive this error seems like my podfile wrong? but I compile in xcode it's fine

**Comment by iceman201** [comment]
![image](https://cloud.githubusercontent.com/assets/5027957/16354659/71d19268-3aef-11e6-8d69-4613a0e864a2.png)

**Comment by viktorbenei** [comment]
Thanks for reporting!

Could you please attach your Podfile? It'd help a lot!

**Comment by iceman201** [comment]
@viktorbenei 

```
platform :ios, '8.0'
use_frameworks!

pod 'RealmSwift'
pod 'EasyAnimation'
pod 'Charts'
pod 'JVFloatLabeledTextField'
pod 'AVOSCloud' 
pod 'AVOSCloudIM'
pod 'CVCalendar', '~> 1.2.9'

target 'GymWorkoutManager' do

end

target 'GymWorkoutManagerTests' do

end

target 'GymWorkoutManagerUITests' do

end


```

**Comment by godrei** [comment]
hi @iceman201 ,
we released a new project scanner version [v0.9.6](https://github.com/bitrise-steplib/steps-project-scanner/releases), it should fixes the podfile analyzer issue.

**Comment by viktorbenei** [comment]
Thanks for reporting the issue @iceman201 - if you have the time and you can test the new scanner (nothing to do, just try to add the same repo again) feel free to report if you'd still have the issue. Otherwise we consider this to be fixed now, feel free to report any issue in the future too! 🚀

**Comment by iceman201** [comment]
Thank you @viktorbenei your team response so quick really appreciate your works
Thank you

**Comment by viktorbenei** [comment]
Thanks, we try to do our best 😊
