### ISSUE TITLE
Failed to get input

### ISSUE THREAD

**Issue by IgorGanapolsky** [bitrise-io/bitrise#369]
Hello,
I am running `bitrise init`, but getting this error:
> A secrets file already exists at ./.bitrise.secrets.yml - do you want to overwrite it? [yes/no] :  
FATA[09:20:14] Failed to init the secrets file, error: Failed to get input - scanner failed. 

Please advise,
Igor

**Comment by viktorbenei** [comment]
Delete the `.bitrise.secrets.yml`, or move to somewhere else ;)

(this is a hidden file if you use Finder)

**Comment by viktorbenei** [comment]
Btw where did you get this? Can you provide a step by step description? Which environment, what commands you ran, etc.

**Comment by IgorGanapolsky** [comment]
Shouldn't the Bitrise tool be smart enough to do that automatically?

**Comment by IgorGanapolsky** [comment]
Mac OS El Capitan.  Following your step-by-step tutorial.  I am an absolute
beginner in Bitrise...

**Comment by viktorbenei** [comment]
No, it won't delete the secrets file automatically, as the secrets file is usually in gitignore - deleting it would cause possible loss of secret infos.

**Comment by viktorbenei** [comment]
Alternatively you can just type in "yes" when the question is asked, letting `bitrise init` to remove it, but any other answer is considered as "no".

**Comment by IgorGanapolsky** [comment]
I'm pretty sure I typed 'yes', or just hit Enter (which is considered same
as 'yes' by every command line program interpreter in the world).

**Comment by viktorbenei** [comment]
> or just hit Enter

That's considered as "no" in this case - because of the possible loss of info/data. You explicitly have to type in "yes" then hit Enter; everything else is considered as "no" in this case.
