### ISSUE TITLE
bash toolkit entry file handling

### ISSUE THREAD

**Issue by godrei** [bitrise-io/bitrise#409]
Implement `entry_file` handling, to allow specify the entry file, instead of hard coding `step.sh` as entry point.

**Comment by viktorbenei** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ob2Y0VaL&#x2F;978-https-github-com-bitrise-io-bitrise-issues-409"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;bitrise-io&#x2F;bitrise&#x2F;issues&#x2F;409</a>

**Comment by godrei** [comment]
released in [v1.4.1](https://github.com/bitrise-io/bitrise/releases/tag/1.4.1)
