### ISSUE TITLE
Install all deps at the start of the build 

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise#414]
This should be an option, most likely the default one

This also requires to get every step at the start of the build 

Why sound this exist? For better build reliability. This could lower the chance of a network issue during the build to cause the build to fail, if it would happen during a dep install

**Comment by godrei** [comment]
Hi @viktorbenei ,
i will close this ticket because of the inactivity around the question.
I hope later we can get back to this feature!

**Comment by viktorbenei** [comment]
Sure, as discussed we don't have a clear use case for this but once we have we can work on it.
