### ISSUE TITLE
No command to download workflow yml?

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-io/bitrise#442]
I know I can download the yml like this:

> curl --fail https://www.bitrise.io/api/app/${BITRISE_APP_SLUG}/config/download.yml?api_token=${BITRISE_APP_API_TOKEN}

but it'd be nice if the cli had a method that enabled backing up all the yaml files. Enabling downloading of an individual yml would be a good start.

**Comment by viktorbenei** [comment]
Definitely planned, once we finalize and roll out the first version of the API. Please comment and vote here: https://bitrise.uservoice.com/forums/235233-general/suggestions/10577118-full-api

**Comment by bootstraponline** [comment]
commented

**Comment by viktorbenei** [comment]
Thanks! :)
