### ISSUE TITLE
Export log

### ISSUE THREAD

**Issue by pouriaalmassi** [bitrise-io/bitrise#481]
Bitrise CLI should provide a flag to write the full log to disk. This would make it easier to read through logs later in the event that a user's terminal is not set to provide an infinite history.

**Comment by trapacska** [comment]
Hey @pouriaalmassi ! 👋🏻

You can collect the logs simply like the following:
`bitrise run myworkflow > /path/to/my/log.log`

Could you please define what would be the main difference if the CLI would do this? It would have a default log path of course, but you would need to set the log path anyway.

Thank you for your feedback!

**Comment by viktorbenei** [comment]
Also, if you want to redirect both the stdout __and__ the stderr:

```
bitrise run myworkflow >>file.txt 2>&1
```

Source: http://stackoverflow.com/questions/876239/how-can-i-redirect-and-append-both-stdout-and-stderr-to-a-file-with-bash

**Comment by viktorbenei** [comment]
Closing as we believe there are existing solutions (built into your shell) which can handle this better than a single parameter. If you disagree @pouriaalmassi just let us know and we'll re-open this ticket! And of course, thanks for creating the ticket here! ;)
