### ISSUE TITLE
bitrise runner CLI failed to run workflow: error bitrise.yml doesn't exist.

### ISSUE THREAD

**Issue by julestburt** [bitrise-io/bitrise#549]
After setting up the runner CLI with brew I cannot get it to run with my existing bitrise.yml.

I created a new folder, put the bitrise.yml file there and did bitrise run bitrise.yml.

This is what I get if I run:
 version: 1.10.1

INFO[10:58:56] Running workflow: bitrise.yml     
FATA[10:58:56] Failed to run workflow, error: Specified Workflow (bitrise.yml) does not exist 

This is what I get if I run bitrise "stepman" "collections" "--format" "json":
{"data":[]}
^^ Not expected I'm sure??

This is what I see after running bitrise setup:
  version: 1.10.1

Setup
Full setup: false
Clean setup: false
Detected OS: darwin

Checking Bitrise Core tools...
[OK] envman (1.1.8): /Users/jules/.bitrise/tools/envman
[OK] stepman (0.9.35): /Users/jules/.bitrise/tools/stepman

Doing OS X specific setup
Checking required tools...
[OK] Homebrew 1.3.8: /usr/local/bin/brew
[OK] Homebrew/homebrew-core (git revision 99ad; last commit 2017-11-27)
[OK] xcodebuild (Xcode 9.1 | Build version 9B55): /usr/bin/xcodebuild
[OK] active Xcode (Command Line Tools) path (xcode-select --print-path): /Applications/Xcode.app/Contents/Developer

Checking Bitrise Plugins...
[OK] Plugin init (0.9.11): /Users/jules/.bitrise/plugins/init
[OK] Plugin step (0.9.5): /Users/jules/.bitrise/plugins/step
[OK] Plugin workflow-editor (1.0.19): /Users/jules/.bitrise/plugins/workflow-editor
[OK] Plugin analytics (0.9.10): /Users/jules/.bitrise/plugins/analytics

Checking Bitrise Toolkits...
[OK] go (1.9.2): /Users/jules/.bitrise/toolkits/go/inst/go/bin/go
[OK] bash (GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)): /bin/bash

All the required tools are installed! We're ready to rock!!

To start using bitrise:
* cd into your project's directory (if you're not there already)
* call: bitrise init
* follow the guide

That's all :)

**Comment by viktorbenei** [comment]
Hi @julestburt,

> and did bitrise run bitrise.yml

You don't have to (and in this case should not) specify `bitrise.yml`. Just `cd` into the directory where you saved it, then:

```
bitrise run
```

to list all workflows, or

```
bitrise run some-workflow
```

to run the workflow "some-workflow".

If you want to run from another directory you can specify where the `bitrise.yml` is located with the `--config` flag passed to run:

```
bitrise run --config /path/to/bitrise.yml some-workflow
```

(to run `some-workflow`, located in the `/path/to/bitrise.yml`).

I'll close this issue but if you have any questions just let us know! :)

**Comment by viktorbenei** [comment]
Ohh, one more thing; I wrote a getting started guide here, which should help with exploring the CLI / experimenting with the CLI: https://discuss.bitrise.io/t/how-to-experiment-with-bitrise-configs-locally-on-your-mac-linux/1751

**Comment by julestburt** [comment]
Thanks - confirmed this was user error! :-)

👍

**Comment by viktorbenei** [comment]
No problem, Happy Building! ;)

**Comment by anuragajwani** [comment]
I was looking for the `--config`, running `bitrise --help` doesn't provide me information about this option

**Comment by fehersanyi-bitrise** [comment]
Hy @anuragajwani 

`--config` was changed to `--init` some time ago.

**Comment by viktorbenei** [comment]
Hey 👋 

@fehersanyi-bitrise no it wasn't changed ;)

@anuragajwani it's not in `bitrise --help` because `--config` is specific to `bitrise run`. If you run `bitrise run --help` to print the help text of `run` / `bitrise run` you'll get:

```
$ bitrise run --help

NAME:
   bitrise run - Runs a specified Workflow.

USAGE:
   bitrise run [command options] [arguments...]

OPTIONS:
   --workflow value             workflow id to run.
   --config value, -c value     Path where the workflow config file is located.
   --inventory value, -i value  Path of the inventory file.
   --secret-filtering           Hide secret values from the log.
   --json-params value          Specify command flags with json string-string hash.
   --json-params-base64 value   Specify command flags with base64 encoded json string-string hash.
   --path value, -p value       [Deprecated!!! Use 'config'] Path where the workflow config file is located.
   --config-base64 value        base64 encoded config data.
   --inventory-base64 value     base64 encoded inventory data.
```

This is a common pattern, that the "root" `--help` just prints all the root options and all the commands, but to see more details about a specific command (in this case about the `run` command) you have to do `--help` for that command specifically (`bitrise run --help`).

I hope this helps!
Happy Building! ;)
