### ISSUE TITLE
Failed to install missing SDK

### ISSUE THREAD

**Issue by fahimsakri** [bitrise-io/bitrise#559]
I recently upgraded `compileSDKVersion` to 27 from 26 and run the `bitrise run primary`, it failed and showing me this error

`earching for missing SDK components using:
$ ./gradlew "dependencies"
[31;1mFailed to find missing components, retrying...[0m
Searching for missing SDK components using:
$ ./gradlew "dependencies"
[31;1mFailed to find missing components, retrying...[0m
Searching for missing SDK components using:
$ ./gradlew "dependencies"
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'workspace'.

Could not resolve all files for configuration ':classpath'.
    Could not find com.android.tools.build:gradle:3.0.1.
`

**Comment by koral--** [comment]
It seems that you don't have google repository configured. See https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#apply_plugin.

**Comment by viktorbenei** [comment]
Hi @fahimsakri ,

@koral-- is right, can you please try the suggested solution and let us know how it goes?
You can also find a bit more info at: https://discuss.bitrise.io/t/couldnt-find-com-android-tools-build-gradle-3-0-0/3170 (check the comments)

**Comment by viktorbenei** [comment]
Ohh, and of course if you'd have any questions just let us know! ;)

**Comment by fahimsakri** [comment]
@koral @viktorbenei Thanks that helped me.

**Comment by viktorbenei** [comment]
Glad to hear and thanks for reporting @fahimsakri ! :)

And thanks @koral-- for chiming in of course! ;)

Closing.
