### ISSUE TITLE
Support for incoming webhook from Crowdin 

### ISSUE THREAD

**Issue by meyn** [bitrise-io/bitrise#586]
would be pretty cool if you could support incoming webhooks from crowdin so we could automatically trigger a workflow (to create a Pull Request to Github with the changed translations)

**Comment by viktorbenei** [comment]
Hi @meyn ,

Great idea! Please:

1. Either submit a pull request at https://github.com/bitrise-io/bitrise-webhooks
1. Or create a feature request at: https://discuss.bitrise.io/c/feature-request

Thanks! :)
