### ISSUE TITLE
You entered a number greater than the last option's number

### ISSUE THREAD

**Issue by kumamoto** [bitrise-io/bitrise#587]
Please drag-and-drop your Xcode Project (.xcodeproj) or Workspace (.xcworkspace) file,
the one you usually open in Xcode, then hit Enter.

(Note: if you have a Workspace file you should most likely use that) : /Users/benleblond/projects/xxxxx/xxxxxx-xxxxx/ios/Runner.xcworkspace

🔦  Running an Xcode Archive, to get all the required code signing settings...
$ xcodebuild "-workspace" "/Users/ben/projects/xxxxxx/xxxxx-xxxx/ios/Runner.xcworkspace" "-scheme" "Runner" "clean" "archive" "-archivePath" "/var/folders/zv/0t8m48451rzcjkvyypwgmsf40000gp/T/__codesigndoc__612486754/Runner.xcarchive"
.................................

💡  Saving xcodebuild output into file: /Users/ben/codesigndoc_exports/xcodebuild-output.log

Codesign settings used for archive:

development team: XXXXXXXX (xxxxx)
codesign identity: iPhone Developer: Ben XXXXXX (xxxxxx) [7594474508909231173]
provisioning profiles: iOS Team Provisioning Profile: xx.xx.helloworld -> xx.xx.helloworld

🔦  Analyzing the archive, to get ipa export code signing settings...

The archive used codesigning files of team: xxxxxx - XXXXXX
Would you like to use this team to sign your project? [YES/no]:

The Xcode archive used development certificate: iPhone Developer: Ben XXXXX (xxxxxx) [7594474508909231173].
Please select a distribution certificate:
Please select from the list:
(type in the option's number, then hit Enter) [1] : 1
failed to read input: invalid option: You entered a number greater than the last option's number

Always get stuck on here.

**Comment by viktorbenei** [comment]
Hi @kumamoto ,

I'll close this here as it doesn't seem to be related to the CLI, but rather to `codesigndoc`.

Can you please re-open this at: https://github.com/bitrise-tools/codesigndoc

Would be really appreciated! :)
