### ISSUE TITLE
Auto script to get provisioning/cert file executed fail

### ISSUE THREAD

**Issue by tonifirnandes** [bitrise-io/bitrise#593]
Hello team,

We need some help.

Auto script to get provisioning/cert file executed fail, error details here :

![image](https://user-images.githubusercontent.com/3122029/39058308-a33b097c-44e5-11e8-84e8-65cc39222c8e.png)

As you can see, left terminal picture shown the script process which return failed, the right terminal picture show if actually in my laptop/local machine has the provisioning files to be used.

Thanks.

**Comment by viktorbenei** [comment]
Hi,

This issue seems to be related to codesigndoc ( https://github.com/bitrise-tools/codesigndoc ) can you please create a new issue there with the log files generated by codesigndoc & the full log output of the Terminal? Would help a lot! :)

**Comment by tonifirnandes** [comment]
Oh hi @viktorbenei , i am really sorry dont know where should put the issue :), thank you veyr much lets discuss on that .
