### ISSUE TITLE
404 link in validation step of Add New App wizard

### ISSUE THREAD

**Issue by danbtl** [bitrise-io/bitrise#611]
The "share your schemes" link points to http://devcenter.bitrise.io/ios/frequent-ios-issues/#xcode-scheme-not-found (404)

![deepinscreenshot_select-area_20180627131718](https://user-images.githubusercontent.com/630781/41989274-bd951374-7a0c-11e8-86a3-2780720aec82.png)

**Comment by godrei** [comment]
Hi @danbtl this is a website issue please report it here: https://discuss.bitrise.io/c/issues/website-issues
