### ISSUE TITLE
How to create app builds for a dynamic base URL

### ISSUE THREAD

**Issue by swarna-sathya** [bitrise-io/bitrise#663]
Hi,

This is not an issue. I was not sure where to reach out to you.

I want to be able to input a base URL while generating the build so that the same app set up will be able to provide builds for different endpoints.

I also want to know if I can set up a react native project on Bitrise.

Can you please help me with it and direct me to the right documentation?

**Comment by fehersanyi-bitrise** [comment]
Hello there

for the first question, I would recommend using an env var in the code, and set up workflow specific environment variables on bitrise, so if you run a dev build, this URL will be the one you set up for the dev build, and if you run a prod workflow, it will be the other one. I hope it is understandable 😅

for the second one, yes absolutely, here is a getting started guide: https://devcenter.bitrise.io/getting-started/getting-started-with-react-native-apps/
