### ISSUE TITLE
Running connectedAndroidTest reaches "Abort via Bitrise DEN (timeout)"

### ISSUE THREAD

**Issue by RoRoche** [bitrise-io/bitrise#714]
Hi everybody,

I add three steps in my workflow:

1. AVD manager
2. wait for Android emulator
3. Gradle unit test (launching Gradle task "connectedAndroidTest")

It passes the 2 first steps but the third reaches "Abort via Bitrise DEN (timeout)".

What could I do to make it pass?

Thanks in advance.

Regards,
Romain.

P.S. : it was the same with the "detekt" step

**Comment by RoRoche** [comment]
Close because timeout is due to free plan timeout set to 10 minutes

**Comment by csk4ta** [comment]
Hello, 

Many teams — including ours — have suddenly found themselves fully remote, in some cases being physically separated from the hardware they used to build and test mobile applications on. To help them adapt, we’ve taken our free Hobby plan and bumped up the build timeout from 10 to 30 minutes.

This means that everyone, for free, can:
- Run 200 builds per month, for any platform, including iOS and Android
- Run builds that take up to 30 minutes to finish
- Can invite up to 2 team members

This means that users on our free plan can now build up to 6,000 minutes per month, free of charge.

Besides assisting teams that suddenly find themselves remote, we hope these changes to our free plan will provide indies, freelancers, and those simply looking to work on their personal projects while stuck at home, a place to build. This offer is valid until the end of July, 2020. I hope this helps!
