### ISSUE TITLE
Add macOS Big Sur support to Homebrew formula

### ISSUE THREAD

**Issue by timtraversy** [bitrise-io/bitrise#731]
The current [Homebrew formula ](https://formulae.brew.sh/api/formula/bitrise.json) points to three tar files for Catalina, High Sierra, and Mojave. Could it be updated to support Big Sur as well? If the current release runs on Big Sur.

Thanks!

**Comment by bitce** [comment]
Hi @timtraversy! Thanks for bringing this to our attention, we've created a task to make this change :)

**Comment by timtraversy** [comment]
This has been fixed! Thanks
