### ISSUE TITLE
Import path should be "github.com/sirupsen/logrus", not "github.com/Sirupsen/logrus"

### ISSUE THREAD

**Issue by KateGo520** [bitrise-io/bitrise#732]
## Background
As [README](https://github.com/sirupsen/logrus/blob/v1.6.0/README.md) of logrus said, `github.com/Sirupsen/logrus` is the old path, anything using it should be updated to import and require `github.com/sirupsen/logrus`.

> Some environments experienced problems with the upper-case variant, so the lower-case was decided. Everything using `logrus` will need to use the lower-case: `github.com/sirupsen/logrus`. Any package that isn't, should be changed.

## Solution
Replace all the import paths, change `"github.com/Sirupsen/logrus"` to `"github.com/sirupsen/logrus"`.
Where did you import it: https://github.com/bitrise-io/bitrise/search?q=github.com%2FSirupsen%2Flogrus&unscoped_q=github.com%2FSirupsen%2Flogrus

**Comment by KateGo520** [comment]
@trapacska  @lpusok  Could you help me review this issue? Thx :p

**Comment by ofalvai** [comment]
I believe this issue has been fixed in a recent Bitrise CLI version, I'm closing this.
