### ISSUE TITLE
Update Bitrise CLI failed

### ISSUE THREAD

**Issue by itsJoKr** [bitrise-io/bitrise#743]
I tried to publish the step, but it looks like after the scripts passed there is bitrise update and it fails.
```
+---+---------------------------------------------------------------+----------+
| ✓ | script                                                        | 8.09 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | script                                                        | 24.42 sec|
+---+---------------------------------------------------------------+----------+
| Total runtime: 32.51 sec                                                     |
+------------------------------------------------------------------------------+


Submitting anonymized usage informations...
For more information visit:
https://github.com/bitrise-io/bitrise-plugins-analytics/blob/master/README.md
Checking for new CLI version...
WARN[13:38:52] failed to check for update, error: failed to check update for CLI, error: exit status 1 
```

Then I tried to manually update:
```
bitrise update
Updating Bitrise CLI...
Current version: 1.38.0
Update Bitrise CLI failed, error: exit status 1
```

Then I tried to get some more info, but that's all I got.
```
bitrise --debug update
WARN[13:51:21] => Started in DEBUG mode                     
WARN[13:51:21] => LogLevel set to debug                     
Updating Bitrise CLI...
Current version: 1.38.0
Update Bitrise CLI failed, error: exit status 1
```

**Comment by Roland-Bak** [comment]
Hello there @itsJoKr 👋

Can you please let us know some details of the step in question?
Would it be possible to check the build and the workflow associated with it?

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look?

**Comment by itsJoKr** [comment]
I actually realized that bitrise CLI did publish a step successfully, but after that (as the last step probably) tried to update itself and failed. So, I was able to proceed with my work on the step.

This is not connected to any specific project. Running `bitrise update` anywhere would fail. I tried to use --debug but as you can see there are no addition logs, so this might be very hard for you to debug.

For me, this is not a blocker right now, as I don't need update. So we can close it, but it might be interesting for you, you can add some more detailed logs for future versions.

**Comment by mr-fixit** [comment]
same issue here...
```
$ bitrise --loglevel debug update
Updating Bitrise CLI...
Current version: 1.38.0
Update Bitrise CLI failed, error: exit status 1
$ bitrise --loglevel info update 
Updating Bitrise CLI...
Current version: 1.38.0
Update Bitrise CLI failed, error: exit status 1
```

**Comment by cathyharmon** [comment]
Hello,

Sorry to hear that you are having this issue.  We have tried to reproduce this but we were not able to.  Given that this version is a bit back-level, I would recommend that you reinstall the latest level, making sure to run `bitrise setup` after installing.

cathy

**Comment by mr-fixit** [comment]
I installed v 1.44.1 with homebrew, still got the same error:
```
$ bitrise update
Updating Bitrise CLI...
Current version: 1.44.1
Update Bitrise CLI failed, error: exit status 1
```

**Comment by cathyharmon** [comment]
Hello,

The latest version is 1.45.1.  Please try the following:

Remove previous version:

`brew uninstall bitrise`

Install bitrise:

`brew update && brew install bitrise`

and then run the setup:

`bitrise setup`
