### ISSUE TITLE
https://devcenter.bitrise.io/getting-started/connecting-apple-dev-account/ does not exist

### ISSUE THREAD

**Issue by ndbeyer** [bitrise-io/bitrise#760]
Something is not working when trying to deploy my app to appstore connect, it has to do with 2FA. So I went to read this guide here `https://devcenter.bitrise.io/deploy/ios-deploy/deploying-an-ios-app-to-itunes-connect/`, but an important link is not working: `https://devcenter.bitrise.io/getting-started/connecting-apple-dev-account/ does not exist`. Please fix this.

**Comment by ofalvai** [comment]
I believe this issue is no longer relevant, the links are working for me on the current page. I'm closing the issue.
