### ISSUE TITLE
BITRISE_XCODE_RAW_TEST_RESULT_TEXT_PATH not exported anymore ?

### ISSUE THREAD

**Issue by SimpleApp** [bitrise-io/bitrise#774]
There seems to have been a change in the XCode run iOS tests step which doesn't export BITRISE_XCODE_RAW_TEST_RESULT_TEXT_PATH anymore (at least my next step "deploy to bitrise.ios" generates an error on the path : missing path.

Can someone confirm this ?

**Comment by Roland-Bak** [comment]
Hello there @SimpleApp 👋

There was a change in  the Xcode test for iOS step, you can check it's release notes in our Github repository (https://github.com/bitrise-steplib/steps-xcode-test/releases), where it is stated that we have replaced the BITRISE_XCODE_RAW_TEST_RESULT_TEXT_PATH environment variable with BITRISE_XCODEBUILD_BUILD_LOG_PATH and BITRISE_XCODEBUILD_TEST_LOG_PATH 🙂 

Hope this helps!
