### ISSUE TITLE
Bitrise triggers not scheduling properly via the Web app

### ISSUE THREAD

**Issue by trod-123** [bitrise-io/bitrise#860]
I've had issues yesterday and today with scheduling Bitrise triggers via the GUI.

1. Refreshing the page after having disabled and reenabled a trigger would change the scheduled time. I wonder if there was a recent timezones update had anything to do with this (we were somehow set on UTC initially; our timezone is GMT-8 Los Angeles).

https://user-images.githubusercontent.com/11514412/224456486-7aaf9304-061b-4c2c-bd27-be6b1ff40cd0.mov

2. Today, I notice that some of our triggers were scheduled with the wrong date and time. I wonder if this is somehow related to the above. We did not change our scheduling. So when I went and fixed the scheduling for one of them, they do not seem to get set right. It looks like they are set to the _next_ day for some reason. Please see video below.

https://user-images.githubusercontent.com/11514412/224456010-00bfa4c9-362d-4579-8c9f-913f9d3b9e68.mov

Needless to say, this has caused delays on our end because we did not realize a trigger did not activate when we expected. Similarly, this has caused triggers firing when we did not expect. I am not sure the prevalence of this issue, given issue channels seem to be quiet about it, but if we can get this resolved soon, that would be much appreciated. Thanks.

**Comment by pilvikala** [comment]
@trod-123 Apologies for the inconvenience, this issue should be fixed now. Can you check and let us know if it still persists for you?

**Comment by viktorbenei** [comment]
Closing this ticket as solved. @trod-123 thanks again for reporting! 🙌
