### ISSUE TITLE
Scanner failed when running `bitrise :step create`, mac m1

### ISSUE THREAD

**Issue by jfacoustic** [bitrise-io/bitrise#879]
When I try to run `bitrise :step create`, I get the following error:

```
Who are you / who's the author? [Joshua Mathews] : What's the title / name of the Step? : ERROR: Failed to determine title: failed to get input - scanner failed
Failed to run plugin (step), error: exit status 255
```

It never prompts me to enter a title, it immediately fails after I run the command.

This is after a fresh bitrise CLI install with both homebrew and curl on a mac m1 pro

**Comment by godrei** [comment]
Hi @jfacoustic , thanks for reporting this issue.
The problem has been fixed in the latest release: https://github.com/bitrise-io/bitrise/releases/tag/2.4.0
