### ISSUE TITLE
deployment to google stores

### ISSUE THREAD

**Issue by Vyrtar** [bitrise-io/bitrise#893]
im currently setting up bitrise for deployment of our react native app

here is my bitrise yml deployment workflow:
    deploy-android:
      steps:
        - script:
            title: Build APK or AAB
            inputs:
              - content: |-
                  cd android
                  ./gradlew bundle$CLUBNAME
                  cd ..
        - google-play-deploy:
              title: Deploy to Google Play
              inputs:
                - service_account_json_key_path: $google_api
                - track: 'internal'
                - user_fraction: '1.0'
                - should_create_track: 'true'
                - should_update_track: 'true'
                - apk_or_aab_path: 'android/app/build/outputs/bundle/friedenauertscRelease'

it crashes on "google-play-deploy" with this error:

Failed to prepare the step for execution through the required toolkit (go), error: failed to build Step in directory (/var/folders/8p/rv64nzjs0jb8wn0ky9vg2r3c0000gn/T/bitrise1189544036/step_src): command `/Users/samuelwoerner/.bitrise/toolkits/go/inst/go/bin/go "build" "-o" "/Users/samuelwoerner/.bitrise/toolkits/go/cache/https___github.com_bitrise-io_bitrise-steplib.git-google-play-deploy"` failed, output: network.go:17:2: //go:build comment without // +build comment
vendor/golang.org/x/oauth2/oauth2.go:21:2: //go:build comment without // +build comment

**Comment by UrbanChrisy** [comment]
@Vyrtar Did you manage to solve? I am getting the same issue at the moment.

**Comment by Vyrtar** [comment]
> @Vyrtar Did you manage to solve? I am getting the same issue at the moment.

re install Go on your system
